name: udsmtaarifalive CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ["self-hosted", "udsmtaarifalive"]
    strategy:
      matrix:
        node-version: [20]

    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm install

      - name: Server Restart
        run: |
          npm install -g pm2
          pm2 stop udsmtaarifalive || true
          pm2 start udsmtaarifalive
          pm2 save
          sudo service nginx restart
